[Settings]
X=2635
Y=33
Width=1750
Height=1025
TempDeviation=50
KTime=10
DeviceID=0
Queue=0
ConfirmationRequest=0
ShowOriginalKTV=0
ShowGladeKTV=1
UseControlComment=0
ControlComment=
LastUserWarning=предупреждение
AutoReset=0
ReportWithDets=1
UseUserWarningComment=1
UseDeviceFilterIndicatorBit=0
DosCntAutoCreatePart=1
SkipDetector=1
DialogType[dNone]=100
DialogType[dInfo]=250
DialogType[dFail]=450
DialogType[dReserv]=150

[Filter]
FCondition=
FSort=ORDER BY measurmenttime DESC
FDosEnable=1
FDosDosNumber=39
FDosOrganization=
FDosDepartment=
FDosDosPath=
FDosDosType=
FDosDosStatus=
FDosPersNumber=
FDosIDK=
FDosTimeFrom=
FDosTimeTo=
FDosComment=
FDosShowAllDevices=1
FProcessEnable=0
FProcessDosNumber=
FProcessOrganization=
FProcessDepartment=
FProcessDosPath=
FProcessDosType=
FProcessDosStatus=
FProcessPersNumber=
FProcessIDK=
FProcessTimeFrom=
FProcessTimeTo=
FProcessResult=
FProcessComment=
FProcessShowDelMeas=0
FProcessShowAllDevices=1
FProcessDevicesID=
FDosDevicesID=
FCalibrEnable=0

[GridColumnsMeas]
ColumnMeasID=1
ColumnMeasDateTime=1
ColumnMeasKSI=1
ColumnMeasDose=1
ColumnMeasHp10g=1
ColumnMeasHp10n=0
ColumnMeasHp007=1
ColumnMeasHp3=1
ColumnMeasHStar=0
ColumnMeasH007=0
ColumnMeasD=0
ColumnMeasHp10g_Err=1
ColumnMeasHp10n_Err=0
ColumnMeasHp007_Err=1
ColumnMeasHp3_Err=1
ColumnMeasHStar_Err=0
ColumnMeasH007_Err=0
ColumnMeasD_Err=0
ColumnMeasValidity=1
ColumnMeasDosType=1
ColumnMeasDosReg=0
ColumnMeasDosVer=0
ColumnMeasDosStatus=0
ColumnMeasOrganization=0
ColumnMeasDepartment=0
ColumnMeasPartID=1
ColumnMeasComment=0
ColumnMeasPersNumber=0
ColumnMeasFIO=0
ColumnMeasTLDUser=0
ColumnMeasLastMeasComment=0
ColumnMeasTldID=1

[GridColumnsProcess]
ColumnProcessID=1
ColumnProcessKSI=1
ColumnProcessDateTime=1
ColumnProcessDose=1
ColumnProcessHp10g=1
ColumnProcessHp10n=1
ColumnProcessHp007=1
ColumnProcessHp3=1
ColumnProcessHStar=1
ColumnProcessH007=0
ColumnProcessD=0
ColumnProcessHp10g_Err=1
ColumnProcessHp10n_Err=1
ColumnProcessHp007_Err=0
ColumnProcessHp3_Err=0
ColumnProcessHStar_Err=1
ColumnProcessH007_Err=0
ColumnProcessD_Err=0
ColumnProcessValidity=0
ColumnProcessDosType=1
ColumnProcessDosReg=0
ColumnProcessDosVer=0
ColumnProcessDosStatus=0
ColumnProcessOrganization=0
ColumnProcessDepartment=0
ColumnProcessPartID=1
ColumnProcessComment=0
ColumnProcessPersNumber=0
ColumnProcessFIO=0
ColumnProcessTLDUser=0
ColumnProcessLastMeasComment=0
ColumnProcessTldID=1

[GridColumnsCalibr]
ColumnCalibrID=1
ColumnCalibrKSI=1
ColumnCalibrDateTime=1
ColumnCalibrDose=1
ColumnCalibrK1=1
ColumnCalibrK2=1
ColumnCalibrK3=1
ColumnCalibrK4=1
ColumnCalibrK5=1
ColumnCalibrKgn=1
ColumnCalibrHp10g=1
ColumnCalibrHp10n=0
ColumnCalibrHp007=1
ColumnCalibrHp3=0
ColumnCalibrHStar=0
ColumnCalibrH007=0
ColumnCalibrD=0
ColumnCalibrHp10g_Err=0
ColumnCalibrHp10n_Err=0
ColumnCalibrHp007_Err=0
ColumnCalibrHp3_Err=0
ColumnCalibrHStar_Err=0
ColumnCalibrH007_Err=0
ColumnCalibrD_Err=0
ColumnCalibrValidity=0
ColumnCalibrDosType=1
ColumnCalibrDosReg=0
ColumnCalibrDosVer=0
ColumnCalibrDosStatus=0
ColumnCalibrOrganization=0
ColumnCalibrDepartment=0
ColumnCalibrPartID=1
ColumnCalibrComment=0
ColumnCalibrPersNumber=0
ColumnCalibrFIO=0
ColumnCalibrTLDUser=0
ColumnCalibrLastMeasComment=0
ColumnCalibrTldID=0

[GridColumnsDos]
ColumnDosType=1
ColumnDosStatus=1
ColumnDosReg=1
ColumnDosVer=1
ColumnOrganization=0
ColumnDepartment=0
ColumnDosk1=0
ColumnDosk2=0
ColumnDosk3=0
ColumnDosk4=0
ColumnDosk5=0
ColumnDoskgn=0
ColumnDosPartID=1
ColumnDosLastMeasTime=1
ColumnDosLastMeasResult=1
ColumnDosLastMeasComment=1
ColumnDosTldID=1
ColumnDosOrganization=0

[COMPortSettings]
COMName=COM2
//COMName=Client192.168.3.94
//COMName=Emulator
BaudRate=115200
StopBits=0
Parity=0
ByteSize=8

[Test]
SourceUse=1
SourceTimeIncrease=0
SourceTimeIncreaseCycle=0
SourceKIncrease=0
SourceTime=0
SourceDosimeterName=1_TEST
WriteModbusLog=1

[DBSettings]
ODBCDriver=Driver={PostgreSQL ANSI}
PGPass=2236
PGPort=5432
PGUid=postgres
ServerIP=localhost
;ServerIP=192.168.1.103
DBName=work
PGRestorePath=C:\Program Files\PostgreSQL\15\bin\pg_restore.exe
PGDumpPath=C:\Program Files\PostgreSQL\15\bin\pg_dump.exe
PGBackupPath=c:\W\Lazarus\DozaTLD_Auto\BackupDB\
PGBackupDays=1
PGTime=31.08.2026 13:20:02

[DB_ASIDK_Settings]
ASIDK_Use=0
ASIDK_ODBCDriver=Driver={PostgreSQL ANSI}
ASIDK_PGPassASIDK=alpha1
ASIDK_PGPort=5432
ASIDK_PGUid=postgres
ASIDK_ServerIP=192.168.1.35
ASIDK_DBName=asidk

[Users]
Administrator=c4ac921e11de5db8f8238bab56dc52721
PowerUser=a855c3b87b681b3b1d068eb83e792b592
User=eccbc87e4b5ce2fe28308fd9f2a7baf33

[CalcForm]
X=778
Y=382
Width=1020
Height=714
SplitLeft=0
SplitDown=0
SavePosition=0
ParametersPanel=1
EditRange_Change=1
VisualChangers_View=1
VisualChangers_Annotation=1
VisualRange_View=1
cbWOFon_View=1
S_View=1
Err_View=1
Menu_View=1
VisualChangers_Use=1
VisualRange_Use=1
EditChart=1
ExitNotifyIfManualChange=1
CalcForm_ShowNegativeDose=0

[GridProcess]
DBGridEhProcess.measurmentid=1,70,0,1,0,7,0,0,1
DBGridEhProcess.tldid=0,110,0,1,0,7,0,0,1
DBGridEhProcess.fulldosid=2,85,0,1,0,7,0,0,1
DBGridEhProcess.dosimetertype=3,120,0,1,0,7,0,0,1
DBGridEhProcess.measurmenttime=4,180,0,1,0,7,0,0,1
DBGridEhProcess.ksi=5,45,0,1,0,7,0,0,1
DBGridEhProcess.dose=6,230,0,1,0,7,0,0,1
DBGridEhProcess.hp10g=7,120,0,1,0,7,0,0,1
DBGridEhProcess.hp10n=8,120,0,1,0,7,0,0,1
DBGridEhProcess.hp007=9,120,0,1,0,7,0,0,1
DBGridEhProcess.hp3=10,120,0,1,0,7,0,0,1
DBGridEhProcess.hstar=11,94,0,0,0,7,0,0,1
DBGridEhProcess.h007=12,94,0,0,0,7,0,0,1
DBGridEhProcess.d=13,94,0,0,0,7,0,0,1
DBGridEhProcess.hp10g_err=14,120,0,1,0,7,0,0,1
DBGridEhProcess.hp10n_err=15,120,0,1,0,7,0,0,1
DBGridEhProcess.hp007_err=16,94,0,0,0,7,0,0,1
DBGridEhProcess.hp3_err=17,94,0,0,0,7,0,0,1
DBGridEhProcess.hstar_err=18,94,0,0,0,7,0,0,1
DBGridEhProcess.h007_err=19,94,0,0,0,7,0,0,1
DBGridEhProcess.d_err=20,94,0,0,0,7,0,0,1
DBGridEhProcess.validity=21,94,0,0,0,7,0,0,1
DBGridEhProcess.stringvalidity=22,73714,0,0,0,7,0,0,1
DBGridEhProcess.regtime=23,166,0,0,0,7,0,0,1
DBGridEhProcess.vertime=24,166,0,0,0,7,0,0,1
DBGridEhProcess.status=25,94,0,0,0,7,0,0,1
DBGridEhProcess.organization=26,73714,0,0,0,7,0,0,1
DBGridEhProcess.department=27,73714,0,0,0,7,0,0,1
DBGridEhProcess.partid=28,94,0,0,0,7,0,0,1
DBGridEhProcess.partname=29,110,0,1,0,7,0,0,1
DBGridEhProcess.lastmeascomment=30,73714,0,0,0,7,0,0,1
DBGridEhProcess.meascomment=31,73714,0,0,0,7,0,0,1
DBGridEhProcess.personalnumber=32,94,0,0,0,7,0,0,1
DBGridEhProcess.fio=33,73714,0,0,0,7,0,0,1
DBGridEhProcess.tlduser=34,73714,0,0,0,7,0,0,1
DBGridEhProcess.to_del=35,49,0,0,0,7,0,0,1

[GridDos]
DBGridEhDos.fulldosid=1,180,0,1,0,7,0,0,1
DBGridEhDos.tldid=0,110,0,1,0,7,0,0,1
DBGridEhDos.dosimeterid=2,94,0,0,0,7,0,0,1
DBGridEhDos.postfix=3,73714,0,0,0,7,0,0,1
DBGridEhDos.dosimetertype=4,120,0,1,0,7,0,0,1
DBGridEhDos.dosimetertypeid=6,94,0,0,0,7,0,0,1
DBGridEhDos.stringstate=7,73714,0,0,0,7,0,0,1
DBGridEhDos.status=8,94,0,0,0,7,0,0,1
DBGridEhDos.k1=5,85,0,1,0,7,0,0,1
DBGridEhDos.k2=9,85,0,0,0,7,0,0,1
DBGridEhDos.k3=10,265,0,0,0,7,0,0,1
DBGridEhDos.k4=11,265,0,0,0,7,0,0,1
DBGridEhDos.k5=12,265,0,0,0,7,0,0,1
DBGridEhDos.kgn=13,85,0,0,0,7,0,0,1
DBGridEhDos.partid=14,94,0,0,0,7,0,0,1
DBGridEhDos.partname=15,110,0,1,0,7,0,0,1
DBGridEhDos.regtime=16,180,0,1,0,7,0,0,1
DBGridEhDos.vertime=17,120,0,1,0,7,0,0,1
DBGridEhDos.organization=18,73714,0,0,0,7,0,0,1
DBGridEhDos.department=19,73714,0,0,0,7,0,0,1
DBGridEhDos.lastmeastime=20,180,0,1,0,7,0,0,1
DBGridEhDos.lastmeasresult=21,94,0,0,0,7,0,0,1
DBGridEhDos.stringvalidity=22,230,0,1,0,7,0,0,1
DBGridEhDos.lastmeascomment=23,110,0,1,0,7,0,0,1

[GridCalibr]
DBGridEhCalcKDos.tldid=25,110,0,0,0,7,0,0,1
DBGridEhCalcKDos.fulldosid=1,85,0,1,0,7,0,0,1
DBGridEhCalcKDos.measurmentid=0,70,0,1,0,7,0,0,1
DBGridEhCalcKDos.dosimetertype=10,120,0,1,0,7,0,0,1
DBGridEhCalcKDos.calibrationvalue=12,110,0,1,0,7,0,0,1
DBGridEhCalcKDos.radiationtype=24,120,0,1,0,7,0,0,1
DBGridEhCalcKDos.k1=26,85,0,1,0,7,0,0,1
DBGridEhCalcKDos.k2=27,85,0,1,0,7,0,0,1
DBGridEhCalcKDos.k3=31,85,0,0,0,7,0,0,1
DBGridEhCalcKDos.k4=30,85,0,0,0,7,0,0,1
DBGridEhCalcKDos.k5=29,85,0,0,0,7,0,0,1
DBGridEhCalcKDos.kgn=28,85,0,1,0,7,0,0,1
DBGridEhCalcKDos.dose=19,230,0,1,0,7,0,0,1
DBGridEhCalcKDos.hp10g=20,120,0,1,0,7,0,0,1
DBGridEhCalcKDos.err_Hp_10g_Percent=8,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.hp10n=23,94,0,0,0,7,0,0,1
DBGridEhCalcKDos.err_Hp_10n_Percent=7,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.hp3=22,94,0,0,0,7,0,0,1
DBGridEhCalcKDos.err_Hp_3_Percent=6,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.hp007=21,120,0,1,0,7,0,0,1
DBGridEhCalcKDos.err_Hp_007_Percent=5,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.hstar=18,94,0,0,0,7,0,0,1
DBGridEhCalcKDos.err_H_star_Percent=4,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.h007=17,94,0,0,0,7,0,0,1
DBGridEhCalcKDos.err_H_007_Percent=3,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.d=16,94,0,0,0,7,0,0,1
DBGridEhCalcKDos.err_D_Percent=2,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.ksi=11,45,0,1,0,7,0,0,1
DBGridEhCalcKDos.formula_id_dos=15,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.partname=13,110,0,1,0,7,0,0,1
DBGridEhCalcKDos.partid=14,184,0,0,0,7,0,0,1
DBGridEhCalcKDos.validity=9,184,0,0,0,7,0,0,1

[GridMeas]
DBGridEhOnlyMeas.measurmentid=0,70,0,1,0,7,0,0,1
DBGridEhOnlyMeas.tldid=1,110,0,1,0,7,0,0,1
DBGridEhOnlyMeas.fulldosid=2,85,0,1,0,7,0,0,1
DBGridEhOnlyMeas.dosimetertype=3,120,0,1,0,7,0,0,1
DBGridEhOnlyMeas.measurmenttime=4,180,0,1,0,7,0,0,1
DBGridEhOnlyMeas.ksi=5,45,0,1,0,7,0,0,1
DBGridEhOnlyMeas.dose=6,230,0,1,0,7,0,0,1
DBGridEhOnlyMeas.hp10g=7,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp10n=8,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp007=9,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp3=10,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hstar=11,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.h007=12,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.d=13,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp10g_err=14,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp10n_err=15,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp007_err=16,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hp3_err=17,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.hstar_err=18,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.h007_err=19,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.d_err=20,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.validity=21,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.stringvalidity=22,180,0,1,0,7,0,0,1
DBGridEhOnlyMeas.regtime=23,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.vertime=24,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.lastmeastime=25,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.status=26,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.organization=27,364,0,0,0,7,0,0,1
DBGridEhOnlyMeas.department=28,364,0,0,0,7,0,0,1
DBGridEhOnlyMeas.partid=29,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.partname=30,110,0,1,0,7,0,0,1
DBGridEhOnlyMeas.lastmeascomment=31,1084,0,0,0,7,0,0,1
DBGridEhOnlyMeas.meascomment=32,1084,0,0,0,7,0,0,1
DBGridEhOnlyMeas.personalnumber=33,94,0,0,0,7,0,0,1
DBGridEhOnlyMeas.fio=34,904,0,0,0,7,0,0,1
DBGridEhOnlyMeas.tlduser=35,454,0,0,0,7,0,0,1
DBGridEhOnlyMeas.to_del=36,49,0,0,0,7,0,0,1

[DeviceUnits]
Monitor.TargetTemp=15
UserPanel.Host=None
UserPanel.MBAddr=1
UserPanel.TimeOut=2
IrradiationEDR=3
Peltier.TargetTemp=15
Old_AirHeat=0
