object MSGWindow: TMSGWindow
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'MSGWindow'
  ClientHeight = 121
  ClientWidth = 154
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDefault
  Scaled = False
  OnActivate = FormActivate
  OnClick = FormClick
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Alarms1Label: TLabel
    Left = 6
    Top = 28
    Width = 38
    Height = 13
    Caption = 'Alarms1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    Visible = False
    OnClick = Alarms1LabelClick
  end
  object Alarms2Label: TLabel
    Left = 6
    Top = 11
    Width = 38
    Height = 13
    Caption = 'Alarms2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    Visible = False
    OnClick = Alarms2LabelClick
  end
  object ServiceLabel: TLabel
    Left = 4
    Top = 79
    Width = 35
    Height = 13
    Caption = 'Service'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    Visible = False
    OnClick = ServiceLabelClick
  end
  object RepairLabel: TLabel
    Left = 6
    Top = 62
    Width = 31
    Height = 13
    Caption = 'Repair'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    Visible = False
    OnClick = RepairLabelClick
  end
  object NoConnectionLabel: TLabel
    Left = 6
    Top = 45
    Width = 67
    Height = 13
    Caption = 'NoConnection'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    Visible = False
    OnClick = NoConnectionLabelClick
  end
  object RectangleShape: TShape
    Left = 0
    Top = 0
    Width = 154
    Height = 121
    Brush.Style = bsClear
    OnMouseDown = RectangleShapeMouseDown
  end
end
